/*
Was just bored so i created a quick little game that plays out as a russian roulette, Basically the revolver class
creates an object that takes your name and puts it in the mag function that uses the random object to create a 6 shooter 
revolver. the random object randomly creates a number between 1 and 6 and the bullet is the number 1 so while the 
random number generated by the random object is 1, the name is declared dead and thus looses, a do-while loop was added for 
you to play with your friends.
*/

import java.util.Scanner;
public class Shimgapi {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		String n;
		String x;
	revolver shoot = new revolver();	
	Scanner keyboard = new Scanner(System.in);	
	String cont;
	System.out.println("Welcome to the russian roulette game!");
	do {
		
		
		System.out.println("What is your name?");
		n = keyboard.nextLine();
		x = shoot.mag(n);
		
		System.out.println( n + " Is " + x);
		System.out.println("---------------------------------------------")
		System.out.println("Would you like to Add another name? (y/n) ");
		cont = keyboard.nextLine();
		
	}
	while(cont.equals("y"));
	
	}

	
	
	
	
	
	
	
}
